config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  match '/404', to: 'errors#not_found',             via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  resources :available_times, only: [:new, :create, :edit, :update]
  resources :employees,       only: [:show, :create, :new, :edit, :update] do
    resources :status, only: :update
  end
  devise_for :admins, path: '',
                      path_names: {
                        sign_in: 'signin',
                        sign_out: 'signout',
                        sign_up: 'signup_for_an_account_admin'
                      },
                      controllers: {
                        registrations: 'registrations'
                      }
  resources :admins,    only: [:show]
  resources :schedules, only: [:show, :index, :new, :create] do
    resources :shifts,              only: [:index, :create]
    resources :associate_employees, only: [:create, :destroy]
  end

  root 'welcome#home'
end

app/views/admins/show.html.erb
<div class='container'>
  <div class='col-md-8'>
    <div>
      <h1>
      <%= t('.greeting', company: @admin.company) %>
    </h1>

    <h2><%= t('.button_header') %></h2>
    <p>
      <%= link_to t('.update_account'), edit_admin_registration_path,
                  class: 'btn btn-default btn-sm' %>
    </p>
    <p>
      <%= link_to t('.add_schedule'), new_schedule_path,
                  class: 'btn btn-default btn-sm' %>
      <%= link_to t('.view_schedules'), schedules_path,
                  class: 'btn btn-default btn-sm' %>
    </p>
    <p>
      <%= link_to t('.add_employee'), new_employee_path,
                  class: 'btn btn-default btn-sm' %>
      <%= link_to t('.add_available_time'), new_available_time_path,
                  class: 'btn btn-default btn-sm' %>

    </p>

    <h2><%= t('.employees_header') %></h2>
    <h3><%= t('.shift_lead_label') %></h3>
      <div class='shift-leads'>
        <% @admin.employees.employees_by_position('Shift Lead').each do |employee| %>
          <div class='active_employee'>
            <%= render partial: 'employees/shift_lead',
                       locals: { employee: employee } %>
          </div>
        <% end %>
      </div>

    <h3><%= t('.team_member_label') %></h3>
      <div class='team-members'>
        <% @admin.employees.employees_by_position('Team Member').each do |employee| %>
          <div class='active_employee'>
            <%= render partial: 'employees/team_member',
                       locals: { employee: employee } %>
          </div>
        <% end %>
      </div>

    <h3><%= t('.inactive_label') %></h3>
      <div>
        <% @admin.employees.inactive_employees.each do |employee| %>
          <div class='inactive_employee'>
            <%= render partial: 'employees/inactive_employee',
                       locals: { employee: employee } %>
          </div>
        <% end %>
      </div>

    </div>
  </div>
</div>