config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  match '/404', to: 'errors#not_found',             via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  resources :available_times, only: [:new, :create, :edit, :update]
  resources :employees,       only: [:show, :create, :new, :edit, :update] do
    resources :status, only: :update
  end
  devise_for :admins, path: '',
                      path_names: {
                        sign_in: 'signin',
                        sign_out: 'signout',
                        sign_up: 'signup_for_an_account_admin'
                      },
                      controllers: {
                        registrations: 'registrations'
                      }
  resources :admins,    only: [:show]
  resources :schedules, only: [:show, :index, :new, :create] do
    resources :shifts,              only: [:index, :create]
    resources :associate_employees, only: [:create, :destroy]
  end

  root 'welcome#home'
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  validates_presence_of :business_year, :business_week
  belongs_to :admin
  has_many :schedule_available_times
  has_many :available_times, through: :schedule_available_times
  has_many :schedule_employees
  has_many :employees, through: :schedule_employees
  has_many :schedule_shifts
  has_many :shifts, through: :schedule_shifts
  accepts_nested_attributes_for :shifts

  def week_and_year
    "Week #{business_week}, #{business_year}"
  end

  def grab_dates(year, week, day)
    Date.commercial(year, week, day).strftime('%m/%d')
  end

  def self.current_admins_only(admin)
    where('admin_id = ?', admin)
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :assign_schedule,       only: [:show]
  before_action :load_employees,        only: [:show]
  before_action :load_employee_times,   only: [:show]
  before_action :load_schedule_shifts,  only: [:show]
  before_action :print_schedule?, only: [:show]

  def index
    @schedules = Schedule.current_admins_only(current_admin)
  end

  def show
  end

  def new
    @schedule = Schedule.new
  end

  def create
    @schedule = Schedule.new(schedule_params)
    @schedule.admin = current_admin

    if @schedule.save
      redirect_to schedule_path(@schedule)
    else
      render :new
    end
  end

  private

  def assign_schedule
    @schedule = Schedule.find(params[:id])
  end

  def schedule_params
    params.require(:schedule).permit(:business_year, :business_week)
  end

  def load_employees
    @team_members = @schedule.employees.employees_by_position('Team Member')
    @shift_leads  = @schedule.employees.employees_by_position('Shift Lead')
  end

  def load_employee_times
    @employee_times = {}
    @schedule.employees.each_with_object({}) do |employee|
      @employee_times[employee] = employee.available_times
    end
  end

  def load_schedule_shifts
    @schedule_shifts = @schedule.shifts
  end

  def print_schedule?
    @printable_view = true if params[:print]
  end
end

app/helpers/schedules_helper.rb
module SchedulesHelper

  def employee_type(employee)
    employee.class == Admin ? 0 : employee.id
  end

  def shifts_created?(day, employee, schedule_shifts)
    if select_shifts_by_day_and_employee(day, employee, schedule_shifts).count.zero?
      @schedule.shifts.build
    else
      select_shifts_by_day_and_employee(day, employee, schedule_shifts)
    end
  end

  def select_employee_times(day, employee, employee_times)
    employee_times[employee].select { |time| time.day_of_week == day }
  end

  def select_shifts_by_day_and_employee(day, employee, schedule_shifts)
    emp_id = employee.has_attribute?(:admin_id) ? employee.id : 0
    schedule_shifts.select do |shift|
      shift.employee_id == emp_id && shift.day_of_week == day
    end
  end

  def which_buttons?(schedule, admin, printable)
    if admin == schedule.admin && @printable_view.nil?
      concat(render(partial: "add_remove_employees"))
      link_to(t('.set_schedule'), schedule_shifts_path(@schedule),
                   class: 'btn btn-default btn-xs')
    end
  end

  def print_view?(schedule, admin, printable)
    if @printable_view.nil?
      link_to(t('.print_schedule'), schedule_path(@schedule, print: true),
                target: '_blank', class: 'btn btn-default btn-xs')
    end
  end
end

app/views/schedules/_add_remove_employees.html.erb
<% if @schedule.employees.none? %>
  <%= link_to t('.add_employees'), schedule_associate_employees_path(@schedule),
              method: :post, class: 'btn btn-success btn-xs' %>
<% else %>
  <%= link_to t('.remove_employees'), schedule_associate_employee_path(@schedule),
              method: :delete, class: 'btn btn-danger btn-xs',
              data: {confirm: 'Are you sure?'} %>
<% end %>

app/views/schedules/_form.html.erb
<%= form_for(@schedule) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <p>
    <%= f.label :business_year %>
    <%= f.text_field :business_year %>
  </p>

  <p>
    <%= f.label :business_week %>
    <%= f.text_field :business_week %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/schedules/_schedule.html.erb
<h2><%= link_to schedule.week_and_year, schedule_path(schedule) %></h2>

app/views/schedules/_set_times_form.html.erb
<%= form_for(@schedule) do |f| %>
  <%= f.label :business_year %>
    <%= f.text_field :biz_year %>
    <%= f.label :business_week %>
    <%= f.text_field :biz_week %>
  <%= f.submit 'Finalize schedule' %>

  <table class="ui green celled striped table unstackable fixed">
    <thead>
      <%= render 'schedules/table/header_days' %>
    </thead>
    <tbody>
      <%= render 'schedules/table/header_dates' %>
      <%= render 'schedules/table/managers', f: f %>
      <%= render 'schedules/table/shift_leads', f: f %>
      <%= render 'schedules/table/team_members', f: f %>
    </tbody>
  </table>
<% end %>

app/views/schedules/_toggle_employees.html.erb
<% if @schedule.employees.none? %>
  <%= link_to t('.add_employees'),
            add_employees_path(@schedule),
            method: :post,
            class: 'ui tiny button green' %>
<% else %>
  <%= link_to t('.remove_employees'),
            remove_employees_path(@schedule),
            method: :post,
            class: 'ui tiny button red',
            data: {confirm: 'Are you sure?'} %>
<% end %>

app/views/schedules/_toggle_shifts.html.erb
<% if @schedule.shifts.none? %>
  <%= link_to t('.add_shifts'),
            add_shifts_path(@schedule),
            method: :post,
            class: 'ui tiny button green' %>
<% else %>
  <%= link_to t('.remove_shifts'),
            remove_shifts_path(@schedule),
            method: :post,
            class: 'ui tiny button red',
            data: {confirm: 'Are you sure?'} %>
<% end %>

app/views/schedules/edit.html.erb
<%= render 'set_shifts_form' %>

app/views/schedules/finalize.html.erb
<table class="ui green celled striped table unstackable fixed">
  <thead>
    <%= render 'schedules/table/header_days' %>
  </thead>
  <tbody>
    <%= render 'schedules/table/header_dates' %>
    <%= render 'schedules/table/managers' %>
    <%= render 'schedules/table/shift_leads' %>
    <%= render 'schedules/table/team_members' %>
  </tbody>
</table>

app/views/schedules/index.html.erb
<div class='container'>
  <h1><%= t('.greeting') %></h1>
    <%= render @schedules %>
</div>

app/views/schedules/new.html.erb
<div class='container'>
  <div class='col-md-6'>
  <h1>Add new schedule</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/schedules/show.html.erb
<div class='container-fluid'>
  <h1>
    Week of
    <%= @schedule.grab_dates(@schedule.business_year, @schedule.business_week, 1) %>
    to <%= @schedule.grab_dates(@schedule.business_year, @schedule.business_week, 7) %>,
    <%= @schedule.business_year %>
  </h1>

  <p>
    <%= which_buttons?(@schedule, current_admin, @printable_view) %>
    <%= print_view?(@schedule, current_admin, @printable_view) %>
  </p>

  <table class="table table-striped table-bordered table-hover">
    <thead>
      <%= render 'schedules/table/header_days' %>
    </thead>
    <tbody>
      <%= render 'schedules/table/header_dates' %>
      <%= render 'schedules/table/managers' %>
      <%= render 'schedules/table/shift_leads' %>
      <%= render 'schedules/table/team_members' %>
    </tbody>
  </table>
</div>