config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  match '/404', to: 'errors#not_found',             via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  resources :available_times, only: [:new, :create, :edit, :update]
  resources :employees,       only: [:show, :create, :new, :edit, :update] do
    resources :status, only: :update
  end
  devise_for :admins, path: '',
                      path_names: {
                        sign_in: 'signin',
                        sign_out: 'signout',
                        sign_up: 'signup_for_an_account_admin'
                      },
                      controllers: {
                        registrations: 'registrations'
                      }
  resources :admins,    only: [:show]
  resources :schedules, only: [:show, :index, :new, :create] do
    resources :shifts,              only: [:index, :create]
    resources :associate_employees, only: [:create, :destroy]
  end

  root 'welcome#home'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home() end
end

app/views/welcome/home.html.erb
<header class="main-header">
  <div class="title">
    <h1 class="header-h1"><%= t('.greeting') %></h1>
    <div class="header-text">
      Create a schedule without the spreadsheet fuss
    </div>
      <p>
        <%= link_to 'Let\'s get started!', new_admin_registration_path,
                    class: 'btn btn-primary' unless admin_signed_in? %>
      </p>
      <p>
        <%= link_to 'Visit your account page to get started', admin_path(current_admin),
                    class: 'btn btn-primary' if admin_signed_in? %>
      </p>
  </div>
</header>
<footer class="container">
  <small>
    &copy; 2017 Developed by <%= link_to "Brian Emory", 'http://www.brianemory.com' %> |
    <%= link_to 'GitHub', 'https://github.com/thebrianemory/schedule-app' %>
  </small>
</footer>